version: '3.4'

services:
    numbersdb:
        container_name: numbersdb
        restart: always
        volumes: 
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"

    primenumbers.api:
        container_name: primenumbersapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "NumbersDatabaseSettings:ConnectionString=mongodb://numbersdb:27017"
        depends_on:
            - numbersdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft.usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet.https
        ports:
            - "8000:80"

    apigateway:
        container_name: apigateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - primenumbers.api
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft.usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet.https
        ports:
            - "7000:80"

    primenumbersplayground:
        container_name: primenumbersplayground
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ApiSettings:BaseAddress=apigateway"
        depends_on:
            - primenumbers.api
            - apigateway
        volumes:
            - ${APPDATA}/.microsoft/usersecrets/:/root/.microsoft.usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        ports:
            - "8001:80"